//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Camera
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoLeave
    {
        public long ImageID { get; set; }
        public string GoAvatar { get; set; }
        public Nullable<System.DateTime> GoDT { get; set; }
        public string GoFull { get; set; }
        public string GoPlate { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<System.DateTime> LeaveDT { get; set; }
        public string LeaveFull { get; set; }
        public string LeavePlate { get; set; }
        public string OutOCR { get; set; }
        public long OwnerID { get; set; }
        public string leaveAvatar { get; set; }
        public bool IsFinish { get; set; }
        public string Note { get; set; }
        public string GoOCR { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
