//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Camera
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Member()
        {
            this.GoLeaves = new HashSet<GoLeave>();
        }
    
        public long ID { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> CreateDT { get; set; }
        public Nullable<System.DateTime> DateIdentityCard { get; set; }
        public Nullable<System.DateTime> DateofBirth { get; set; }
        public string FirstMidName { get; set; }
        public Nullable<long> ImageID { get; set; }
        public bool IsDeleted { get; set; }
        public string LastName { get; set; }
        public string MobilePhone { get; set; }
        public int Sex { get; set; }
        public int Status { get; set; }
        public int StudentID { get; set; }
        public int UniversityID { get; set; }
        public Nullable<System.DateTime> UpdateDT { get; set; }
        public string WhereIdentityCard { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoLeave> GoLeaves { get; set; }
    }
}
